### ISSUE TITLE
Problems to install.

### ISSUE THREAD

**Issue by rharael** [jwpleow/pytesseract_imagerenamer#1]
First of all I had nothing installed at my computer. Then I get anaconda first. But could'n do anything with it. So I get the Phyton python-3.8.1. installed lots of modules (every error asking for a module, i had to search how to solve it, so now i know how to install lots of modules Yeah.
But I still got stucked at the "pip install rawpy pytesseract opencv-python" step.

Can anyone please help me. or at least show me a video or something telling how to install and at least use the scrit from zero.

C:\Users\loure>pip install rawpy pytesseract opencv-python

Collecting rawpy
  Using cached rawpy-0.13.1.tar.gz (116 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\loure\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\loure\\AppData\\Local\\Temp\\pip-install-h_fkzcf_\\rawpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\loure\\AppData\\Local\\Temp\\pip-install-h_fkzcf_\\rawpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\loure\AppData\Local\Temp\pip-install-h_fkzcf_\rawpy\pip-egg-info'
         cwd: C:\Users\loure\AppData\Local\Temp\pip-install-h_fkzcf_\rawpy\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\loure\AppData\Local\Temp\pip-install-h_fkzcf_\rawpy\setup.py", line 294, in <module>
        windows_libraw_compile()
      File "C:\Users\loure\AppData\Local\Temp\pip-install-h_fkzcf_\rawpy\setup.py", line 151, in windows_libraw_compile
        clone_submodules()
      File "C:\Users\loure\AppData\Local\Temp\pip-install-h_fkzcf_\rawpy\setup.py", line 132, in clone_submodules
        shutil.copy('external/LibRaw-cmake/CMakeLists.txt', 'external/LibRaw/CMakeLists.txt')
      File "c:\users\loure\appdata\local\programs\python\python38-32\lib\shutil.py", line 409, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "c:\users\loure\appdata\local\programs\python\python38-32\lib\shutil.py", line 259, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: 'external/LibRaw-cmake/CMakeLists.txt'
    LibRaw git submodule is not cloned yet, will invoke "git submodule update --init" now
    copying CMake scripts from LibRaw-cmake repository
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Please Help What I am doing wrong?

**Comment by jwpleow** [comment]
@rharael It seems you downloaded both Anaconda and python38-32, but Anaconda already comes with its own Python interpreter, which could be causing conflict. I suggest you try uninstalling python38-32 and try again from step `pip install rawpy pytesseract opencv-python` in command prompt or anaconda prompt. If the same error occurs, could you give the output of `pip --version` and `python --version`?

**Comment by rharael** [comment]
C:\Users\loure>pip --version
pip 20.0.2 from c:\users\loure\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)

C:\Users\loure>python --version
Python 3.8.1


after uninstalling python38-32
 and testing -install rawpy 

pip install rawpy
Collecting rawpy
  Using cached rawpy-0.13.1.tar.gz (116 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\loure\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\loure\\AppData\\Local\\Temp\\pip-install-du4beccf\\rawpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\loure\\AppData\\Local\\Temp\\pip-install-du4beccf\\rawpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\loure\AppData\Local\Temp\pip-install-du4beccf\rawpy\pip-egg-info'
         cwd: C:\Users\loure\AppData\Local\Temp\pip-install-du4beccf\rawpy\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\loure\AppData\Local\Temp\pip-install-du4beccf\rawpy\setup.py", line 294, in <module>
        windows_libraw_compile()
      File "C:\Users\loure\AppData\Local\Temp\pip-install-du4beccf\rawpy\setup.py", line 151, in windows_libraw_compile
        clone_submodules()
      File "C:\Users\loure\AppData\Local\Temp\pip-install-du4beccf\rawpy\setup.py", line 132, in clone_submodules
        shutil.copy('external/LibRaw-cmake/CMakeLists.txt', 'external/LibRaw/CMakeLists.txt')
      File "c:\users\loure\appdata\local\programs\python\python38-32\lib\shutil.py", line 409, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "c:\users\loure\appdata\local\programs\python\python38-32\lib\shutil.py", line 259, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: 'external/LibRaw-cmake/CMakeLists.txt'
    LibRaw git submodule is not cloned yet, will invoke "git submodule update --init" now
    copying CMake scripts from LibRaw-cmake repository
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


same

**Comment by jwpleow** [comment]
@rharael Hmm it's strange that it's still trying to use "c:\users\loure\appdata\local\programs\python\python38-32\" when it should be trying to use Anaconda, which usually has a path like "C:\ProgramData\Anaconda3". I suggest you check your system's PATH and make sure any paths to your old Python installation "c:\users\loure\appdata\local\programs\python\python38-32\" are removed. 

To do this - assuming you're using Windows 10:
1. Search for "path" in windows search - it should bring up something like "Edit the system environment variables". Click it.
2. On the new window - click Environment Variables
3. On the newer window - for both the top ("user variables") and bottom ("system variables") menu, look for the Variable named 'Path', click it, and then click Edit
4. Look for any lines that have something like "c:\users\loure\appdata\local\programs\python\python38-32\" and delete them
5. Your system variables Path should have the following lines (assuming you installed Anaconda for the system):
C:\ProgramData\Anaconda3
C:\ProgramData\Anaconda3\Scripts
C:\ProgramData\Anaconda3\Library\bin

and also

C:\Program Files\Tesseract-OCR
if you're planning on running Tesseract/my script

(or alternatively [follow this stackoverflow thread on how to delete Python](https://stackoverflow.com/questions/3515673/how-to-completely-remove-python-from-a-windows-machine))

You can check where your python installation by typing in the command line:
`python -c "import sys; print(sys.executable)"`
It should be something like "C:\ProgramData\Anaconda3\python.exe"

You should also check your pip's location:
`where pip`
It should be something like "c:\programdata\anaconda3\lib\site-packages"
